### ISSUE TITLE
Unresolved dependency com.gilt.sbt#sbt-aspectjweaver:0.0.1

### ISSUE THREAD

**Issue by molp** [gilt/sbt-aspectjweaver#1]
Hi!

I added the plugin as described in the readme. Unfortunately this leads to a unresolved dependency error.

When I try to find the dependency in bintray.com myself I cannot find it either: https://bintray.com/search?query=sbt-aspectjweaver

Am I doing something wrong?

**Comment by fiadliel** [comment]
Sorry for the delay replying here, didn't see the post.

The extra resolver I documented didn't have the right Ivy/Maven layout, and the problem was masked because I had the library built locally.

I've requested now that this be added to the central SBT plugin repository; when that happens, the need for an extra resolver should go away.

**Comment by fiadliel** [comment]
Now available from https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases - README updated.
